from google import genai
from google.genai import types
import os
import json
import traceback
from dotenv import load_dotenv
from typing import List, Dict, Any
from pydantic import BaseModel
from schemas import Resource

# Load API Key Explicitly
load_dotenv()

class CostItem(BaseModel):
    resource_id: str
    resource_type: str
    estimated_cost: float
    explanation: str

class CostReport(BaseModel):
    total_monthly_cost: float
    currency: str = "USD"
    breakdown: List[CostItem]
    disclaimer: str = "Estimates generated by AI based on public pricing data. Actual AWS costs may vary."

class CostEstimator:
    def __init__(self):
        # Use Pro model for better reasoning on pricing
        self.client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
        self.model_name = "gemini-2.0-flash" # defaulting keeping speed, user had 2.5-pro in comment but 2.0-flash is standard for new SDK unless 2.5 verified 

    def estimate_costs(self, resources: List[Resource]) -> CostReport:
        if not resources:
            return CostReport(total_monthly_cost=0.0, breakdown=[])

        # Prepare context
        resource_summary = []
        for res in resources:
            resource_summary.append({
                "id": res.id,
                "type": res.type,
                "properties": res.properties
            })

        prompt = f"""
        You are an AWS Pricing Expert. 
        Calculate the ESTIMATED MONTHLY COST (USD) for the following infrastructure.
        
        Resources:
        {json.dumps(resource_summary, indent=2)}
        
        Instructions:
        1. Analyze 'instance_type', 'volume_size', 'engine', etc.
        2. Use standard on-demand pricing for us-east-1.
        3. If free tier eligible (e.g. t2.micro first 750h), assume $0 for the first instance, but charge for others.
        4. Return STRICT JSON matching this schema:
        {{
            "total_monthly_cost": 123.45,
            "breakdown": [
                {{ "resource_id": "web-1", "resource_type": "aws_instance", "estimated_cost": 10.0, "explanation": "t2.micro (~$0.0116/hr) * 730 hrs" }}
            ]
        }}
        """

        try:
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
                config=types.GenerateContentConfig(response_mime_type="application/json")
            )
            data = json.loads(response.text)
            return CostReport(**data)
        except Exception as e:
            print(f"Cost Estimation Failed: {e}")
            traceback.print_exc() # Print full stack trace for debugging
            # Fallback
            return CostReport(
                total_monthly_cost=0.0, 
                breakdown=[], 
                disclaimer="Cost estimation service temporarily unavailable."
            )
